using ArcGIS.Core.CIM;
using ArcGIS.Core.Data;
using Google.OrTools.LinearSolver;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using Constraint = Google.OrTools.LinearSolver.Constraint;

namespace SMGI_Common
{
    public class ORTools
    {

        public static void Solve()
        {
            // 创建线性规划求解器
            Solver solver = new Solver("LinearProgrammingExample", Solver.OptimizationProblemType.GLOP_LINEAR_PROGRAMMING);

            // 定义变量
            Variable C3 = solver.MakeNumVar(0, double.PositiveInfinity, "C3");
            Variable D3 = solver.MakeNumVar(0, double.PositiveInfinity, "D3");
            Variable E3= solver.MakeNumVar(0, double.PositiveInfinity, "E3");
            Variable F3 = solver.MakeNumVar(0, double.PositiveInfinity, "F3");
            Variable G3 = solver.MakeNumVar(0, double.PositiveInfinity, "G3");
            Variable H3 = solver.MakeNumVar(0, double.PositiveInfinity, "H3");
            Variable I3 = solver.MakeNumVar(0, double.PositiveInfinity, "I3");
            Variable J3 = solver.MakeNumVar(0, double.PositiveInfinity, "J3");
            Variable K3 = solver.MakeNumVar(0, double.PositiveInfinity, "K3");
            Variable L3 = solver.MakeNumVar(0, double.PositiveInfinity, "L3");
            Variable M3 = solver.MakeNumVar(0, double.PositiveInfinity, "M3");
            Variable N3 = solver.MakeNumVar(0, double.PositiveInfinity, "N3");
            Variable O3 = solver.MakeNumVar(0, double.PositiveInfinity, "O3");
            Variable P3 = solver.MakeNumVar(0, double.PositiveInfinity, "P3");
            Variable Q3 = solver.MakeNumVar(0, double.PositiveInfinity, "Q3");

            Variable C4 = solver.MakeNumVar(0, double.PositiveInfinity, "C4");
            Variable D4 = solver.MakeNumVar(0, double.PositiveInfinity, "D4");
            Variable E4= solver.MakeNumVar(0, double.PositiveInfinity, "E4");
            Variable F4 = solver.MakeNumVar(0, double.PositiveInfinity, "F4");
            Variable G4 = solver.MakeNumVar(0, double.PositiveInfinity, "G4");
            Variable H4 = solver.MakeNumVar(0, double.PositiveInfinity, "H4");
            Variable I4 = solver.MakeNumVar(0, double.PositiveInfinity, "I4");
            Variable J4 = solver.MakeNumVar(0, double.PositiveInfinity, "J4");
            Variable K4 = solver.MakeNumVar(0, double.PositiveInfinity, "K4");
            Variable L4 = solver.MakeNumVar(0, double.PositiveInfinity, "L4");
            Variable M4 = solver.MakeNumVar(0, double.PositiveInfinity, "M4");
            Variable N4 = solver.MakeNumVar(0, double.PositiveInfinity, "N4");
            Variable O4 = solver.MakeNumVar(0, double.PositiveInfinity, "O4");
            Variable P4 = solver.MakeNumVar(0, double.PositiveInfinity, "P4");
            Variable Q4 = solver.MakeNumVar(0, double.PositiveInfinity, "Q4");


            Variable C5 = solver.MakeNumVar(0, double.PositiveInfinity, "C5");
            Variable D5 = solver.MakeNumVar(0, double.PositiveInfinity, "D5");
            Variable E5 = solver.MakeNumVar(0, double.PositiveInfinity, "E5");
            Variable F5 = solver.MakeNumVar(0, double.PositiveInfinity, "F5");
            Variable G5 = solver.MakeNumVar(0, double.PositiveInfinity, "G5");
            Variable H5 = solver.MakeNumVar(0, double.PositiveInfinity, "H5");
            Variable I5 = solver.MakeNumVar(0, double.PositiveInfinity, "I5");
            Variable J5 = solver.MakeNumVar(0, double.PositiveInfinity, "J5");
            Variable K5 = solver.MakeNumVar(0, double.PositiveInfinity, "K5");
            Variable L5 = solver.MakeNumVar(0, double.PositiveInfinity, "L5");
            Variable M5 = solver.MakeNumVar(0, double.PositiveInfinity, "M5");
            Variable N5 = solver.MakeNumVar(0, double.PositiveInfinity, "N5");
            Variable O5 = solver.MakeNumVar(0, double.PositiveInfinity, "O5");
            Variable P5 = solver.MakeNumVar(0, double.PositiveInfinity, "P5");
            Variable Q5 = solver.MakeNumVar(0, double.PositiveInfinity, "Q5");


            Variable C6 = solver.MakeNumVar(0, double.PositiveInfinity, "C6");
            Variable D6 = solver.MakeNumVar(0, double.PositiveInfinity, "D6");
            Variable E6 = solver.MakeNumVar(0, double.PositiveInfinity, "E6");
            Variable F6 = solver.MakeNumVar(0, double.PositiveInfinity, "F6");
            Variable G6 = solver.MakeNumVar(0, double.PositiveInfinity, "G6");
            Variable H6 = solver.MakeNumVar(0, double.PositiveInfinity, "H6");
            Variable I6 = solver.MakeNumVar(0, double.PositiveInfinity, "I6");
            Variable J6 = solver.MakeNumVar(0, double.PositiveInfinity, "J6");
            Variable K6 = solver.MakeNumVar(0, double.PositiveInfinity, "K6");
            Variable L6 = solver.MakeNumVar(0, double.PositiveInfinity, "L6");
            Variable M6 = solver.MakeNumVar(0, double.PositiveInfinity, "M6");
            Variable N6 = solver.MakeNumVar(0, double.PositiveInfinity, "N6");
            Variable O6 = solver.MakeNumVar(0, double.PositiveInfinity, "O6");
            Variable P6 = solver.MakeNumVar(0, double.PositiveInfinity, "P6");
            Variable Q6 = solver.MakeNumVar(0, double.PositiveInfinity, "Q6");

            Variable C7 = solver.MakeNumVar(0, double.PositiveInfinity, "C7");
            Variable D7 = solver.MakeNumVar(0, double.PositiveInfinity, "D7");
            Variable E7 = solver.MakeNumVar(0, double.PositiveInfinity, "E7");
            Variable F7 = solver.MakeNumVar(0, double.PositiveInfinity, "F7");
            Variable G7 = solver.MakeNumVar(0, double.PositiveInfinity, "G7");
            Variable H7 = solver.MakeNumVar(0, double.PositiveInfinity, "H7");
            Variable I7 = solver.MakeNumVar(0, double.PositiveInfinity, "I7");
            Variable J7 = solver.MakeNumVar(0, double.PositiveInfinity, "J7");
            Variable K7 = solver.MakeNumVar(0, double.PositiveInfinity, "K7");
            Variable L7 = solver.MakeNumVar(0, double.PositiveInfinity, "L7");
            Variable M7 = solver.MakeNumVar(0, double.PositiveInfinity, "M7");
            Variable N7 = solver.MakeNumVar(0, double.PositiveInfinity, "N7");
            Variable O7 = solver.MakeNumVar(0, double.PositiveInfinity, "O7");
            Variable P7 = solver.MakeNumVar(0, double.PositiveInfinity, "P7");
            Variable Q7 = solver.MakeNumVar(0, double.PositiveInfinity, "Q7");

            Variable C8 = solver.MakeNumVar(0, double.PositiveInfinity, "C8");
            Variable D8 = solver.MakeNumVar(0, double.PositiveInfinity, "D8");
            Variable E8 = solver.MakeNumVar(0, double.PositiveInfinity, "E8");
            Variable F8 = solver.MakeNumVar(0, double.PositiveInfinity, "F8");
            Variable G8 = solver.MakeNumVar(0, double.PositiveInfinity, "G8");
            Variable H8 = solver.MakeNumVar(0, double.PositiveInfinity, "H8");
            Variable I8 = solver.MakeNumVar(0, double.PositiveInfinity, "I8");
            Variable J8 = solver.MakeNumVar(0, double.PositiveInfinity, "J8");
            Variable K8 = solver.MakeNumVar(0, double.PositiveInfinity, "K8");
            Variable L8 = solver.MakeNumVar(0, double.PositiveInfinity, "L8");
            Variable M8 = solver.MakeNumVar(0, double.PositiveInfinity, "M8");
            Variable N8 = solver.MakeNumVar(0, double.PositiveInfinity, "N8");
            Variable O8 = solver.MakeNumVar(0, double.PositiveInfinity, "O8");
            Variable P8 = solver.MakeNumVar(0, double.PositiveInfinity, "P8");
            Variable Q8 = solver.MakeNumVar(0, double.PositiveInfinity, "Q8");

            Variable C9 = solver.MakeNumVar(0, double.PositiveInfinity, "C9");
            Variable D9 = solver.MakeNumVar(0, double.PositiveInfinity, "D9");
            Variable E9 = solver.MakeNumVar(0, double.PositiveInfinity, "E9");
            Variable F9 = solver.MakeNumVar(0, double.PositiveInfinity, "F9");
            Variable G9 = solver.MakeNumVar(0, double.PositiveInfinity, "G9");
            Variable H9 = solver.MakeNumVar(0, double.PositiveInfinity, "H9");
            Variable I9 = solver.MakeNumVar(0, double.PositiveInfinity, "I9");
            Variable J9 = solver.MakeNumVar(0, double.PositiveInfinity, "J9");
            Variable K9 = solver.MakeNumVar(0, double.PositiveInfinity, "K9");
            Variable L9 = solver.MakeNumVar(0, double.PositiveInfinity, "L9");
            Variable M9 = solver.MakeNumVar(0, double.PositiveInfinity, "M9");
            Variable N9 = solver.MakeNumVar(0, double.PositiveInfinity, "N9");
            Variable O9 = solver.MakeNumVar(0, double.PositiveInfinity, "O9");
            Variable P9 = solver.MakeNumVar(0, double.PositiveInfinity, "P9");
            Variable Q9 = solver.MakeNumVar(0, double.PositiveInfinity, "Q9");

            Variable C10 = solver.MakeNumVar(0, double.PositiveInfinity, "C10");
            Variable D10 = solver.MakeNumVar(0, double.PositiveInfinity, "D10");
            Variable E10 = solver.MakeNumVar(0, double.PositiveInfinity, "E10");
            Variable F10 = solver.MakeNumVar(0, double.PositiveInfinity, "F10");
            Variable G10 = solver.MakeNumVar(0, double.PositiveInfinity, "G10");
            Variable H10 = solver.MakeNumVar(0, double.PositiveInfinity, "H10");
            Variable I10 = solver.MakeNumVar(0, double.PositiveInfinity, "I10");
            Variable J10 = solver.MakeNumVar(0, double.PositiveInfinity, "J10");
            Variable K10 = solver.MakeNumVar(0, double.PositiveInfinity, "K10");
            Variable L10 = solver.MakeNumVar(0, double.PositiveInfinity, "L10");
            Variable M10 = solver.MakeNumVar(0, double.PositiveInfinity, "M10");
            Variable N10 = solver.MakeNumVar(0, double.PositiveInfinity, "N10");
            Variable O10 = solver.MakeNumVar(0, double.PositiveInfinity, "O10");
            Variable P10 = solver.MakeNumVar(0, double.PositiveInfinity, "P10");
            Variable Q10 = solver.MakeNumVar(0, double.PositiveInfinity, "Q10");

            Variable C11 = solver.MakeNumVar(0, double.PositiveInfinity, "C11");
            Variable D11 = solver.MakeNumVar(0, double.PositiveInfinity, "D11");
            Variable E11 = solver.MakeNumVar(0, double.PositiveInfinity, "E11");
            Variable F11 = solver.MakeNumVar(0, double.PositiveInfinity, "F11");
            Variable G11 = solver.MakeNumVar(0, double.PositiveInfinity, "G11");
            Variable H11 = solver.MakeNumVar(0, double.PositiveInfinity, "H11");
            Variable I11 = solver.MakeNumVar(0, double.PositiveInfinity, "I11");
            Variable J11 = solver.MakeNumVar(0, double.PositiveInfinity, "J11");
            Variable K11 = solver.MakeNumVar(0, double.PositiveInfinity, "K11");
            Variable L11 = solver.MakeNumVar(0, double.PositiveInfinity, "L11");
            Variable M11 = solver.MakeNumVar(0, double.PositiveInfinity, "M11");
            Variable N11 = solver.MakeNumVar(0, double.PositiveInfinity, "N11");
            Variable O11 = solver.MakeNumVar(0, double.PositiveInfinity, "O11");
            Variable P11 = solver.MakeNumVar(0, double.PositiveInfinity, "P11");
            Variable Q11 = solver.MakeNumVar(0, double.PositiveInfinity, "Q11");

            Variable C12 = solver.MakeNumVar(0, double.PositiveInfinity, "C12");
            Variable D12 = solver.MakeNumVar(0, double.PositiveInfinity, "D12");
            Variable E12 = solver.MakeNumVar(0, double.PositiveInfinity, "E12");
            Variable F12 = solver.MakeNumVar(0, double.PositiveInfinity, "F12");
            Variable G12 = solver.MakeNumVar(0, double.PositiveInfinity, "G12");
            Variable H12 = solver.MakeNumVar(0, double.PositiveInfinity, "H12");
            Variable I12 = solver.MakeNumVar(0, double.PositiveInfinity, "I12");
            Variable J12 = solver.MakeNumVar(0, double.PositiveInfinity, "J12");
            Variable K12 = solver.MakeNumVar(0, double.PositiveInfinity, "K12");
            Variable L12 = solver.MakeNumVar(0, double.PositiveInfinity, "L12");
            Variable M12 = solver.MakeNumVar(0, double.PositiveInfinity, "M12");
            Variable N12 = solver.MakeNumVar(0, double.PositiveInfinity, "N12");
            Variable O12 = solver.MakeNumVar(0, double.PositiveInfinity, "O12");
            Variable P12 = solver.MakeNumVar(0, double.PositiveInfinity, "P12");
            Variable Q12 = solver.MakeNumVar(0, double.PositiveInfinity, "Q12");

            Variable C13 = solver.MakeNumVar(0, double.PositiveInfinity, "C13");
            Variable D13 = solver.MakeNumVar(0, double.PositiveInfinity, "D13");
            Variable E13 = solver.MakeNumVar(0, double.PositiveInfinity, "E13");
            Variable F13 = solver.MakeNumVar(0, double.PositiveInfinity, "F13");
            Variable G13 = solver.MakeNumVar(0, double.PositiveInfinity, "G13");
            Variable H13 = solver.MakeNumVar(0, double.PositiveInfinity, "H13");
            Variable I13 = solver.MakeNumVar(0, double.PositiveInfinity, "I13");
            Variable J13 = solver.MakeNumVar(0, double.PositiveInfinity, "J13");
            Variable K13 = solver.MakeNumVar(0, double.PositiveInfinity, "K13");
            Variable L13 = solver.MakeNumVar(0, double.PositiveInfinity, "L13");
            Variable M13 = solver.MakeNumVar(0, double.PositiveInfinity, "M13");
            Variable N13 = solver.MakeNumVar(0, double.PositiveInfinity, "N13");
            Variable O13 = solver.MakeNumVar(0, double.PositiveInfinity, "O13");
            Variable P13 = solver.MakeNumVar(0, double.PositiveInfinity, "P13");
            Variable Q13 = solver.MakeNumVar(0, double.PositiveInfinity, "Q13");

            Variable C14 = solver.MakeNumVar(0, double.PositiveInfinity, "C14");
            Variable D14 = solver.MakeNumVar(0, double.PositiveInfinity, "D14");
            Variable E14 = solver.MakeNumVar(0, double.PositiveInfinity, "E14");
            Variable F14 = solver.MakeNumVar(0, double.PositiveInfinity, "F14");
            Variable G14 = solver.MakeNumVar(0, double.PositiveInfinity, "G14");
            Variable H14 = solver.MakeNumVar(0, double.PositiveInfinity, "H14");
            Variable I14 = solver.MakeNumVar(0, double.PositiveInfinity, "I14");
            Variable J14 = solver.MakeNumVar(0, double.PositiveInfinity, "J14");
            Variable K14 = solver.MakeNumVar(0, double.PositiveInfinity, "K14");
            Variable L14 = solver.MakeNumVar(0, double.PositiveInfinity, "L14");
            Variable M14 = solver.MakeNumVar(0, double.PositiveInfinity, "M14");
            Variable N14 = solver.MakeNumVar(0, double.PositiveInfinity, "N14");
            Variable O14 = solver.MakeNumVar(0, double.PositiveInfinity, "O14");
            Variable P14 = solver.MakeNumVar(0, double.PositiveInfinity, "P14");
            Variable Q14 = solver.MakeNumVar(0, double.PositiveInfinity, "Q14");

            Variable C15 = solver.MakeNumVar(0, double.PositiveInfinity, "C15");
            Variable D15 = solver.MakeNumVar(0, double.PositiveInfinity, "D15");
            Variable E15 = solver.MakeNumVar(0, double.PositiveInfinity, "E15");
            Variable F15 = solver.MakeNumVar(0, double.PositiveInfinity, "F15");
            Variable G15 = solver.MakeNumVar(0, double.PositiveInfinity, "G15");
            Variable H15 = solver.MakeNumVar(0, double.PositiveInfinity, "H15");
            Variable I15 = solver.MakeNumVar(0, double.PositiveInfinity, "I15");
            Variable J15 = solver.MakeNumVar(0, double.PositiveInfinity, "J15");
            Variable K15 = solver.MakeNumVar(0, double.PositiveInfinity, "K15");
            Variable L15 = solver.MakeNumVar(0, double.PositiveInfinity, "L15");
            Variable M15 = solver.MakeNumVar(0, double.PositiveInfinity, "M15");
            Variable N15 = solver.MakeNumVar(0, double.PositiveInfinity, "N15");
            Variable O15 = solver.MakeNumVar(0, double.PositiveInfinity, "O15");
            Variable P15 = solver.MakeNumVar(0, double.PositiveInfinity, "P15");
            Variable Q15 = solver.MakeNumVar(0, double.PositiveInfinity, "Q15");

            Variable C16 = solver.MakeNumVar(0, double.PositiveInfinity, "C16");
            Variable D16 = solver.MakeNumVar(0, double.PositiveInfinity, "D16");
            Variable E16 = solver.MakeNumVar(0, double.PositiveInfinity, "E16");
            Variable F16 = solver.MakeNumVar(0, double.PositiveInfinity, "F16");
            Variable G16 = solver.MakeNumVar(0, double.PositiveInfinity, "G16");
            Variable H16 = solver.MakeNumVar(0, double.PositiveInfinity, "H16");
            Variable I16 = solver.MakeNumVar(0, double.PositiveInfinity, "I16");
            Variable J16 = solver.MakeNumVar(0, double.PositiveInfinity, "J16");
            Variable K16 = solver.MakeNumVar(0, double.PositiveInfinity, "K16");
            Variable L16 = solver.MakeNumVar(0, double.PositiveInfinity, "L16");
            Variable M16 = solver.MakeNumVar(0, double.PositiveInfinity, "M16");
            Variable N16 = solver.MakeNumVar(0, double.PositiveInfinity, "N16");
            Variable O16 = solver.MakeNumVar(0, double.PositiveInfinity, "O16");
            Variable P16 = solver.MakeNumVar(0, double.PositiveInfinity, "P16");
            Variable Q16 = solver.MakeNumVar(0, double.PositiveInfinity, "Q16");

            Variable C17 = solver.MakeNumVar(0, double.PositiveInfinity, "C17");
            Variable D17 = solver.MakeNumVar(0, double.PositiveInfinity, "D17");
            Variable E17 = solver.MakeNumVar(0, double.PositiveInfinity, "E17");
            Variable F17 = solver.MakeNumVar(0, double.PositiveInfinity, "F17");
            Variable G17 = solver.MakeNumVar(0, double.PositiveInfinity, "G17");
            Variable H17 = solver.MakeNumVar(0, double.PositiveInfinity, "H17");
            Variable I17 = solver.MakeNumVar(0, double.PositiveInfinity, "I17");
            Variable J17 = solver.MakeNumVar(0, double.PositiveInfinity, "J17");
            Variable K17 = solver.MakeNumVar(0, double.PositiveInfinity, "K17");
            Variable L17 = solver.MakeNumVar(0, double.PositiveInfinity, "L17");
            Variable M17 = solver.MakeNumVar(0, double.PositiveInfinity, "M17");
            Variable N17 = solver.MakeNumVar(0, double.PositiveInfinity, "N17");
            Variable O17 = solver.MakeNumVar(0, double.PositiveInfinity, "O17");
            Variable P17 = solver.MakeNumVar(0, double.PositiveInfinity, "P17");
            Variable Q17 = solver.MakeNumVar(0, double.PositiveInfinity, "Q17");

            Variable C18 = solver.MakeNumVar(0, double.PositiveInfinity, "C18");
            Variable D18 = solver.MakeNumVar(0, double.PositiveInfinity, "D18");
            Variable E18 = solver.MakeNumVar(0, double.PositiveInfinity, "E18");
            Variable F18 = solver.MakeNumVar(0, double.PositiveInfinity, "F18");
            Variable G18 = solver.MakeNumVar(0, double.PositiveInfinity, "G18");
            Variable H18 = solver.MakeNumVar(0, double.PositiveInfinity, "H18");
            Variable I18 = solver.MakeNumVar(0, double.PositiveInfinity, "I18");
            Variable J18 = solver.MakeNumVar(0, double.PositiveInfinity, "J18");
            Variable K18 = solver.MakeNumVar(0, double.PositiveInfinity, "K18");
            Variable L18 = solver.MakeNumVar(0, double.PositiveInfinity, "L18");
            Variable M18 = solver.MakeNumVar(0, double.PositiveInfinity, "M18");
            Variable N18 = solver.MakeNumVar(0, double.PositiveInfinity, "N18");
            Variable O18 = solver.MakeNumVar(0, double.PositiveInfinity, "O18");
            Variable P18 = solver.MakeNumVar(0, double.PositiveInfinity, "P18");
            Variable Q18 = solver.MakeNumVar(0, double.PositiveInfinity, "Q18");

            Variable C19 = solver.MakeNumVar(0, double.PositiveInfinity, "C19");
            Variable D19 = solver.MakeNumVar(0, double.PositiveInfinity, "D19");
            Variable E19 = solver.MakeNumVar(0, double.PositiveInfinity, "E19");
            Variable F19 = solver.MakeNumVar(0, double.PositiveInfinity, "F19");
            Variable G19 = solver.MakeNumVar(0, double.PositiveInfinity, "G19");
            Variable H19 = solver.MakeNumVar(0, double.PositiveInfinity, "H19");
            Variable I19 = solver.MakeNumVar(0, double.PositiveInfinity, "I19");
            Variable J19 = solver.MakeNumVar(0, double.PositiveInfinity, "J19");
            Variable K19 = solver.MakeNumVar(0, double.PositiveInfinity, "K19");
            Variable L19 = solver.MakeNumVar(0, double.PositiveInfinity, "L19");
            Variable M19 = solver.MakeNumVar(0, double.PositiveInfinity, "M19");
            Variable N19 = solver.MakeNumVar(0, double.PositiveInfinity, "N19");
            Variable O19 = solver.MakeNumVar(0, double.PositiveInfinity, "O19");
            Variable P19 = solver.MakeNumVar(0, double.PositiveInfinity, "P19");
            Variable Q19 = solver.MakeNumVar(0, double.PositiveInfinity, "Q19");

            Variable C20 = solver.MakeNumVar(0, double.PositiveInfinity, "C20");
            Variable D20 = solver.MakeNumVar(0, double.PositiveInfinity, "D20");
            Variable E20 = solver.MakeNumVar(0, double.PositiveInfinity, "E20");
            Variable F20 = solver.MakeNumVar(0, double.PositiveInfinity, "F20");
            Variable G20 = solver.MakeNumVar(0, double.PositiveInfinity, "G20");
            Variable H20 = solver.MakeNumVar(0, double.PositiveInfinity, "H20");
            Variable I20 = solver.MakeNumVar(0, double.PositiveInfinity, "I20");
            Variable J20 = solver.MakeNumVar(0, double.PositiveInfinity, "J20");
            Variable K20 = solver.MakeNumVar(0, double.PositiveInfinity, "K20");
            Variable L20 = solver.MakeNumVar(0, double.PositiveInfinity, "L20");
            Variable M20 = solver.MakeNumVar(0, double.PositiveInfinity, "M20");
            Variable N20 = solver.MakeNumVar(0, double.PositiveInfinity, "N20");
            Variable O20 = solver.MakeNumVar(0, double.PositiveInfinity, "O20");
            Variable P20 = solver.MakeNumVar(0, double.PositiveInfinity, "P20");
            Variable Q20 = solver.MakeNumVar(0, double.PositiveInfinity, "Q20");

            Variable C21 = solver.MakeNumVar(0, double.PositiveInfinity, "C21");
            Variable D21 = solver.MakeNumVar(0, double.PositiveInfinity, "D21");
            Variable E21 = solver.MakeNumVar(0, double.PositiveInfinity, "E21");
            Variable F21 = solver.MakeNumVar(0, double.PositiveInfinity, "F21");
            Variable G21 = solver.MakeNumVar(0, double.PositiveInfinity, "G21");
            Variable H21 = solver.MakeNumVar(0, double.PositiveInfinity, "H21");
            Variable I21 = solver.MakeNumVar(0, double.PositiveInfinity, "I21");
            Variable J21 = solver.MakeNumVar(0, double.PositiveInfinity, "J21");
            Variable K21 = solver.MakeNumVar(0, double.PositiveInfinity, "K21");
            Variable L21 = solver.MakeNumVar(0, double.PositiveInfinity, "L21");
            Variable M21 = solver.MakeNumVar(0, double.PositiveInfinity, "M21");
            Variable N21 = solver.MakeNumVar(0, double.PositiveInfinity, "N21");
            Variable O21 = solver.MakeNumVar(0, double.PositiveInfinity, "O21");
            Variable P21 = solver.MakeNumVar(0, double.PositiveInfinity, "P21");
            Variable Q21 = solver.MakeNumVar(0, double.PositiveInfinity, "Q21");

            Variable C22 = solver.MakeNumVar(0, double.PositiveInfinity, "C22");
            Variable D22 = solver.MakeNumVar(0, double.PositiveInfinity, "D22");
            Variable E22 = solver.MakeNumVar(0, double.PositiveInfinity, "E22");
            Variable F22 = solver.MakeNumVar(0, double.PositiveInfinity, "F22");
            Variable G22 = solver.MakeNumVar(0, double.PositiveInfinity, "G22");
            Variable H22 = solver.MakeNumVar(0, double.PositiveInfinity, "H22");
            Variable I22 = solver.MakeNumVar(0, double.PositiveInfinity, "I22");
            Variable J22 = solver.MakeNumVar(0, double.PositiveInfinity, "J22");
            Variable K22 = solver.MakeNumVar(0, double.PositiveInfinity, "K22");
            Variable L22 = solver.MakeNumVar(0, double.PositiveInfinity, "L22");
            Variable M22 = solver.MakeNumVar(0, double.PositiveInfinity, "M22");
            Variable N22 = solver.MakeNumVar(0, double.PositiveInfinity, "N22");
            Variable O22 = solver.MakeNumVar(0, double.PositiveInfinity, "O22");
            Variable P22 = solver.MakeNumVar(0, double.PositiveInfinity, "P22");
            Variable Q22 = solver.MakeNumVar(0, double.PositiveInfinity, "Q22");

            Variable C23 = solver.MakeNumVar(0, double.PositiveInfinity, "C23");
            Variable D23 = solver.MakeNumVar(0, double.PositiveInfinity, "D23");
            Variable E23 = solver.MakeNumVar(0, double.PositiveInfinity, "E23");
            Variable F23 = solver.MakeNumVar(0, double.PositiveInfinity, "F23");
            Variable G23 = solver.MakeNumVar(0, double.PositiveInfinity, "G23");
            Variable H23 = solver.MakeNumVar(0, double.PositiveInfinity, "H23");
            Variable I23 = solver.MakeNumVar(0, double.PositiveInfinity, "I23");
            Variable J23 = solver.MakeNumVar(0, double.PositiveInfinity, "J23");
            Variable K23 = solver.MakeNumVar(0, double.PositiveInfinity, "K23");
            Variable L23 = solver.MakeNumVar(0, double.PositiveInfinity, "L23");
            Variable M23 = solver.MakeNumVar(0, double.PositiveInfinity, "M23");
            Variable N23 = solver.MakeNumVar(0, double.PositiveInfinity, "N23");
            Variable O23 = solver.MakeNumVar(0, double.PositiveInfinity, "O23");
            Variable P23 = solver.MakeNumVar(0, double.PositiveInfinity, "P23");
            Variable Q23 = solver.MakeNumVar(0, double.PositiveInfinity, "Q23");

            // 添加约束条件
            Constraint constraint1 = solver.MakeConstraint(10000, 10000);
            constraint1.SetCoefficient(C3, 1);
            constraint1.SetCoefficient(D3, 1);
            constraint1.SetCoefficient(E3, 1);
            constraint1.SetCoefficient(D3, 1);
            constraint1.SetCoefficient(F3, 1);
            constraint1.SetCoefficient(G3, 1);
            constraint1.SetCoefficient(H3, 1);
            constraint1.SetCoefficient(I3, 1);
            constraint1.SetCoefficient(J3, 1);
            constraint1.SetCoefficient(K3, 1);
            constraint1.SetCoefficient(L3, 1);
            constraint1.SetCoefficient(M3, 1);
            constraint1.SetCoefficient(N3, 1);
            constraint1.SetCoefficient(O3, 1);
            constraint1.SetCoefficient(P3, 1);
            constraint1.SetCoefficient(Q3, 1);

            Constraint constraint2 = solver.MakeConstraint(5000, 5000);
            constraint2.SetCoefficient(C4, 1);
            constraint2.SetCoefficient(D4, 1);
            constraint2.SetCoefficient(E4, 1);
            constraint2.SetCoefficient(D4, 1);
            constraint2.SetCoefficient(F4, 1);
            constraint2.SetCoefficient(G4, 1);
            constraint2.SetCoefficient(H4, 1);
            constraint2.SetCoefficient(I4, 1);
            constraint2.SetCoefficient(J4, 1);
            constraint2.SetCoefficient(K4, 1);
            constraint2.SetCoefficient(L4, 1);
            constraint2.SetCoefficient(M4, 1);
            constraint2.SetCoefficient(N4, 1);
            constraint2.SetCoefficient(O4, 1);
            constraint2.SetCoefficient(P4, 1);
            constraint2.SetCoefficient(Q4, 1);

            Constraint constraint3 = solver.MakeConstraint(10000, 10000);
            constraint3.SetCoefficient(C5, 1);
            constraint3.SetCoefficient(D5, 1);
            constraint3.SetCoefficient(E5, 1);
            constraint3.SetCoefficient(D5, 1);
            constraint3.SetCoefficient(F5, 1);
            constraint3.SetCoefficient(G5, 1);
            constraint3.SetCoefficient(H5, 1);
            constraint3.SetCoefficient(I5, 1);
            constraint3.SetCoefficient(J5, 1);
            constraint3.SetCoefficient(K5, 1);
            constraint3.SetCoefficient(L5, 1);
            constraint3.SetCoefficient(M5, 1);
            constraint3.SetCoefficient(N5, 1);
            constraint3.SetCoefficient(O5, 1);
            constraint3.SetCoefficient(P5, 1);
            constraint3.SetCoefficient(Q5, 1);

            Constraint constraint4 = solver.MakeConstraint(5000, 5000);
            constraint4.SetCoefficient(C6, 1);
            constraint4.SetCoefficient(D6, 1);
            constraint4.SetCoefficient(E6, 1);
            constraint4.SetCoefficient(D6, 1);
            constraint4.SetCoefficient(F6, 1);
            constraint4.SetCoefficient(G6, 1);
            constraint4.SetCoefficient(H6, 1);
            constraint4.SetCoefficient(I6, 1);
            constraint4.SetCoefficient(J6, 1);
            constraint4.SetCoefficient(K6, 1);
            constraint4.SetCoefficient(L6, 1);
            constraint4.SetCoefficient(M6, 1);
            constraint4.SetCoefficient(N6, 1);
            constraint4.SetCoefficient(O6, 1);
            constraint4.SetCoefficient(P6, 1);
            constraint4.SetCoefficient(Q6, 1);

            Constraint constraint5 = solver.MakeConstraint(5000, 5000);
            constraint5.SetCoefficient(C7, 1);
            constraint5.SetCoefficient(D7, 1);
            constraint5.SetCoefficient(E7, 1);
            constraint5.SetCoefficient(D7, 1);
            constraint5.SetCoefficient(F7, 1);
            constraint5.SetCoefficient(G7, 1);
            constraint5.SetCoefficient(H7, 1);
            constraint5.SetCoefficient(I7, 1);
            constraint5.SetCoefficient(J7, 1);
            constraint5.SetCoefficient(K7, 1);
            constraint5.SetCoefficient(L7, 1);
            constraint5.SetCoefficient(M7, 1);
            constraint5.SetCoefficient(N7, 1);
            constraint5.SetCoefficient(O7, 1);
            constraint5.SetCoefficient(P7, 1);
            constraint5.SetCoefficient(Q7, 1);

            Constraint constraint6 = solver.MakeConstraint(5000, 5000);
            constraint6.SetCoefficient(C8, 1);
            constraint6.SetCoefficient(D8, 1);
            constraint6.SetCoefficient(E8, 1);
            constraint6.SetCoefficient(D8, 1);
            constraint6.SetCoefficient(F8, 1);
            constraint6.SetCoefficient(G8, 1);
            constraint6.SetCoefficient(H8, 1);
            constraint6.SetCoefficient(I8, 1);
            constraint6.SetCoefficient(J8, 1);
            constraint6.SetCoefficient(K8, 1);
            constraint6.SetCoefficient(L8, 1);
            constraint6.SetCoefficient(M8, 1);
            constraint6.SetCoefficient(N8, 1);
            constraint6.SetCoefficient(O8, 1);
            constraint6.SetCoefficient(P8, 1);
            constraint6.SetCoefficient(Q8, 1);

            Constraint constraint7 = solver.MakeConstraint(5000, 5000);
            constraint7.SetCoefficient(C9, 1);
            constraint7.SetCoefficient(D9, 1);
            constraint7.SetCoefficient(E9, 1);
            constraint7.SetCoefficient(D9, 1);
            constraint7.SetCoefficient(F9, 1);
            constraint7.SetCoefficient(G9, 1);
            constraint7.SetCoefficient(H9, 1);
            constraint7.SetCoefficient(I9, 1);
            constraint7.SetCoefficient(J9, 1);
            constraint7.SetCoefficient(K9, 1);
            constraint7.SetCoefficient(L9, 1);
            constraint7.SetCoefficient(M9, 1);
            constraint7.SetCoefficient(N9, 1);
            constraint7.SetCoefficient(O9, 1);
            constraint7.SetCoefficient(P9, 1);
            constraint7.SetCoefficient(Q9, 1);

            Constraint constraint8 = solver.MakeConstraint(5000, 5000);
            constraint8.SetCoefficient(C10, 1);
            constraint8.SetCoefficient(D10, 1);
            constraint8.SetCoefficient(E10, 1);
            constraint8.SetCoefficient(D10, 1);
            constraint8.SetCoefficient(F10, 1);
            constraint8.SetCoefficient(G10, 1);
            constraint8.SetCoefficient(H10, 1);
            constraint8.SetCoefficient(I10, 1);
            constraint8.SetCoefficient(J10, 1);
            constraint8.SetCoefficient(K10, 1);
            constraint8.SetCoefficient(L10, 1);
            constraint8.SetCoefficient(M10, 1);
            constraint8.SetCoefficient(N10, 1);
            constraint8.SetCoefficient(O10, 1);
            constraint8.SetCoefficient(P10, 1);
            constraint8.SetCoefficient(Q10, 1);

            Constraint constraint9 = solver.MakeConstraint(5000, 5000);
            constraint9.SetCoefficient(C11, 1);
            constraint9.SetCoefficient(D11, 1);
            constraint9.SetCoefficient(E11, 1);
            constraint9.SetCoefficient(D11, 1);
            constraint9.SetCoefficient(F11, 1);
            constraint9.SetCoefficient(G11, 1);
            constraint9.SetCoefficient(H11, 1);
            constraint9.SetCoefficient(I11, 1);
            constraint9.SetCoefficient(J11, 1);
            constraint9.SetCoefficient(K11, 1);
            constraint9.SetCoefficient(L11, 1);
            constraint9.SetCoefficient(M11, 1);
            constraint9.SetCoefficient(N11, 1);
            constraint9.SetCoefficient(O11, 1);
            constraint9.SetCoefficient(P11, 1);
            constraint9.SetCoefficient(Q11, 1);

            Constraint constraint10 = solver.MakeConstraint(10000, 10000);
            constraint10.SetCoefficient(C12, 1);
            constraint10.SetCoefficient(D12, 1);
            constraint10.SetCoefficient(E12, 1);
            constraint10.SetCoefficient(D12, 1);
            constraint10.SetCoefficient(F12, 1);
            constraint10.SetCoefficient(G12, 1);
            constraint10.SetCoefficient(H12, 1);
            constraint10.SetCoefficient(I12, 1);
            constraint10.SetCoefficient(J12, 1);
            constraint10.SetCoefficient(K12, 1);
            constraint10.SetCoefficient(L12, 1);
            constraint10.SetCoefficient(M12, 1);
            constraint10.SetCoefficient(N12, 1);
            constraint10.SetCoefficient(O12, 1);
            constraint10.SetCoefficient(P12, 1);
            constraint10.SetCoefficient(Q12, 1);

            Constraint constraint11 = solver.MakeConstraint(10000, 10000);
            constraint11.SetCoefficient(C13, 1);
            constraint11.SetCoefficient(D13, 1);
            constraint11.SetCoefficient(E13, 1);
            constraint11.SetCoefficient(D13, 1);
            constraint11.SetCoefficient(F13, 1);
            constraint11.SetCoefficient(G13, 1);
            constraint11.SetCoefficient(H13, 1);
            constraint11.SetCoefficient(I13, 1);
            constraint11.SetCoefficient(J13, 1);
            constraint11.SetCoefficient(K13, 1);
            constraint11.SetCoefficient(L13, 1);
            constraint11.SetCoefficient(M13, 1);
            constraint11.SetCoefficient(N13, 1);
            constraint11.SetCoefficient(O13, 1);
            constraint11.SetCoefficient(P13, 1);
            constraint11.SetCoefficient(Q13, 1);

            Constraint constraint12 = solver.MakeConstraint(5000, 5000);
            constraint12.SetCoefficient(C14, 1);
            constraint12.SetCoefficient(D14, 1);
            constraint12.SetCoefficient(E14, 1);
            constraint12.SetCoefficient(D14, 1);
            constraint12.SetCoefficient(F14, 1);
            constraint12.SetCoefficient(G14, 1);
            constraint12.SetCoefficient(H14, 1);
            constraint12.SetCoefficient(I14, 1);
            constraint12.SetCoefficient(J14, 1);
            constraint12.SetCoefficient(K14, 1);
            constraint12.SetCoefficient(L14, 1);
            constraint12.SetCoefficient(M14, 1);
            constraint12.SetCoefficient(N14, 1);
            constraint12.SetCoefficient(O14, 1);
            constraint12.SetCoefficient(P14, 1);
            constraint12.SetCoefficient(Q14, 1);

            Constraint constraint13 = solver.MakeConstraint(5000, 5000);
            constraint13.SetCoefficient(C15, 1);
            constraint13.SetCoefficient(D15, 1);
            constraint13.SetCoefficient(E15, 1);
            constraint13.SetCoefficient(D15, 1);
            constraint13.SetCoefficient(F15, 1);
            constraint13.SetCoefficient(G15, 1);
            constraint13.SetCoefficient(H15, 1);
            constraint13.SetCoefficient(I15, 1);
            constraint13.SetCoefficient(J15, 1);
            constraint13.SetCoefficient(K15, 1);
            constraint13.SetCoefficient(L15, 1);
            constraint13.SetCoefficient(M15, 1);
            constraint13.SetCoefficient(N15, 1);
            constraint13.SetCoefficient(O15, 1);
            constraint13.SetCoefficient(P15, 1);
            constraint13.SetCoefficient(Q15, 1);

            Constraint constraint14 = solver.MakeConstraint(5000, 5000);
            constraint14.SetCoefficient(C16, 1);
            constraint14.SetCoefficient(D16, 1);
            constraint14.SetCoefficient(E16, 1);
            constraint14.SetCoefficient(D16, 1);
            constraint14.SetCoefficient(F16, 1);
            constraint14.SetCoefficient(G16, 1);
            constraint14.SetCoefficient(H16, 1);
            constraint14.SetCoefficient(I16, 1);
            constraint14.SetCoefficient(J16, 1);
            constraint14.SetCoefficient(K16, 1);
            constraint14.SetCoefficient(L16, 1);
            constraint14.SetCoefficient(M16, 1);
            constraint14.SetCoefficient(N16, 1);
            constraint14.SetCoefficient(O16, 1);
            constraint14.SetCoefficient(P16, 1);
            constraint14.SetCoefficient(Q16, 1);

            Constraint constraint15 = solver.MakeConstraint(5000, 5000);
            constraint15.SetCoefficient(C17, 1);
            constraint15.SetCoefficient(D17, 1);
            constraint15.SetCoefficient(E17, 1);
            constraint15.SetCoefficient(D17, 1);
            constraint15.SetCoefficient(F17, 1);
            constraint15.SetCoefficient(G17, 1);
            constraint15.SetCoefficient(H17, 1);
            constraint15.SetCoefficient(I17, 1);
            constraint15.SetCoefficient(J17, 1);
            constraint15.SetCoefficient(K17, 1);
            constraint15.SetCoefficient(L17, 1);
            constraint15.SetCoefficient(M17, 1);
            constraint15.SetCoefficient(N17, 1);
            constraint15.SetCoefficient(O17, 1);
            constraint15.SetCoefficient(P17, 1);
            constraint15.SetCoefficient(Q17, 1);

            Constraint constraint16 = solver.MakeConstraint(5000, 5000);
            constraint16.SetCoefficient(C18, 1);
            constraint16.SetCoefficient(D18, 1);
            constraint16.SetCoefficient(E18, 1);
            constraint16.SetCoefficient(D18, 1);
            constraint16.SetCoefficient(F18, 1);
            constraint16.SetCoefficient(G18, 1);
            constraint16.SetCoefficient(H18, 1);
            constraint16.SetCoefficient(I18, 1);
            constraint16.SetCoefficient(J18, 1);
            constraint16.SetCoefficient(K18, 1);
            constraint16.SetCoefficient(L18, 1);
            constraint16.SetCoefficient(M18, 1);
            constraint16.SetCoefficient(N18, 1);
            constraint16.SetCoefficient(O18, 1);
            constraint16.SetCoefficient(P18, 1);
            constraint16.SetCoefficient(Q18, 1);

            Constraint constraint17 = solver.MakeConstraint(10000, 10000);
            constraint17.SetCoefficient(C19, 1);
            constraint17.SetCoefficient(D19, 1);
            constraint17.SetCoefficient(E19, 1);
            constraint17.SetCoefficient(D19, 1);
            constraint17.SetCoefficient(F19, 1);
            constraint17.SetCoefficient(G19, 1);
            constraint17.SetCoefficient(H19, 1);
            constraint17.SetCoefficient(I19, 1);
            constraint17.SetCoefficient(J19, 1);
            constraint17.SetCoefficient(K19, 1);
            constraint17.SetCoefficient(L19, 1);
            constraint17.SetCoefficient(M19, 1);
            constraint17.SetCoefficient(N19, 1);
            constraint17.SetCoefficient(O19, 1);
            constraint17.SetCoefficient(P19, 1);
            constraint17.SetCoefficient(Q19, 1);

            Constraint constraint18 = solver.MakeConstraint(5000, 5000);
            constraint18.SetCoefficient(C20, 1);
            constraint18.SetCoefficient(D20, 1);
            constraint18.SetCoefficient(E20, 1);
            constraint18.SetCoefficient(D20, 1);
            constraint18.SetCoefficient(F20, 1);
            constraint18.SetCoefficient(G20, 1);
            constraint18.SetCoefficient(H20, 1);
            constraint18.SetCoefficient(I20, 1);
            constraint18.SetCoefficient(J20, 1);
            constraint18.SetCoefficient(K20, 1);
            constraint18.SetCoefficient(L20, 1);
            constraint18.SetCoefficient(M20, 1);
            constraint18.SetCoefficient(N20, 1);
            constraint18.SetCoefficient(O20, 1);
            constraint18.SetCoefficient(P20, 1);
            constraint18.SetCoefficient(Q20, 1);

            Constraint constraint19 = solver.MakeConstraint(5000, 5000);
            constraint19.SetCoefficient(C21, 1);
            constraint19.SetCoefficient(D21, 1);
            constraint19.SetCoefficient(E21, 1);
            constraint19.SetCoefficient(D21, 1);
            constraint19.SetCoefficient(F21, 1);
            constraint19.SetCoefficient(G21, 1);
            constraint19.SetCoefficient(H21, 1);
            constraint19.SetCoefficient(I21, 1);
            constraint19.SetCoefficient(J21, 1);
            constraint19.SetCoefficient(K21, 1);
            constraint19.SetCoefficient(L21, 1);
            constraint19.SetCoefficient(M21, 1);
            constraint19.SetCoefficient(N21, 1);
            constraint19.SetCoefficient(O21, 1);
            constraint19.SetCoefficient(P21, 1);
            constraint19.SetCoefficient(Q21, 1);

            Constraint constraint20 = solver.MakeConstraint(10000, 10000);
            constraint20.SetCoefficient(C22, 1);
            constraint20.SetCoefficient(D22, 1);
            constraint20.SetCoefficient(E22, 1);
            constraint20.SetCoefficient(D22, 1);
            constraint20.SetCoefficient(F22, 1);
            constraint20.SetCoefficient(G22, 1);
            constraint20.SetCoefficient(H22, 1);
            constraint20.SetCoefficient(I22, 1);
            constraint20.SetCoefficient(J22, 1);
            constraint20.SetCoefficient(K22, 1);
            constraint20.SetCoefficient(L22, 1);
            constraint20.SetCoefficient(M22, 1);
            constraint20.SetCoefficient(N22, 1);
            constraint20.SetCoefficient(O22, 1);
            constraint20.SetCoefficient(P22, 1);
            constraint20.SetCoefficient(Q22, 1);

            Constraint constraint21 = solver.MakeConstraint(10000, 10000);
            constraint21.SetCoefficient(C23, 1);
            constraint21.SetCoefficient(D23, 1);
            constraint21.SetCoefficient(E23, 1);
            constraint21.SetCoefficient(D23, 1);
            constraint21.SetCoefficient(F23, 1);
            constraint21.SetCoefficient(G23, 1);
            constraint21.SetCoefficient(H23, 1);
            constraint21.SetCoefficient(I23, 1);
            constraint21.SetCoefficient(J23, 1);
            constraint21.SetCoefficient(K23, 1);
            constraint21.SetCoefficient(L23, 1);
            constraint21.SetCoefficient(M23, 1);
            constraint21.SetCoefficient(N23, 1);
            constraint21.SetCoefficient(O23, 1);
            constraint21.SetCoefficient(P23, 1);
            constraint21.SetCoefficient(Q23, 1);

            Constraint constraint22 = solver.MakeConstraint(8800, 8800);
            constraint22.SetCoefficient(C3, 1);
            constraint22.SetCoefficient(C4, 1);
            constraint22.SetCoefficient(C5, 1);
            constraint22.SetCoefficient(C6, 1);
            constraint22.SetCoefficient(C7, 1);
            constraint22.SetCoefficient(C8, 1);
            constraint22.SetCoefficient(C9, 1);
            constraint22.SetCoefficient(C10, 1);
            constraint22.SetCoefficient(C11, 1);
            constraint22.SetCoefficient(C12, 1);
            constraint22.SetCoefficient(C13, 1);
            constraint22.SetCoefficient(C14, 1);
            constraint22.SetCoefficient(C15, 1);
            constraint22.SetCoefficient(C16, 1);
            constraint22.SetCoefficient(C17, 1);
            constraint22.SetCoefficient(C18, 1);
            constraint22.SetCoefficient(C19, 1);
            constraint22.SetCoefficient(C20, 1);
            constraint22.SetCoefficient(C21, 1);
            constraint22.SetCoefficient(C22, 1);
            constraint22.SetCoefficient(C23, 1);

            Constraint constraint23 = solver.MakeConstraint(8800, 8800);
            constraint23.SetCoefficient(D3, 1);
            constraint23.SetCoefficient(D4, 1);
            constraint23.SetCoefficient(D5, 1);
            constraint23.SetCoefficient(D6, 1);
            constraint23.SetCoefficient(D7, 1);
            constraint23.SetCoefficient(D8, 1);
            constraint23.SetCoefficient(D9, 1);
            constraint23.SetCoefficient(D10, 1);
            constraint23.SetCoefficient(D11, 1);
            constraint23.SetCoefficient(D12, 1);
            constraint23.SetCoefficient(D13, 1);
            constraint23.SetCoefficient(D14, 1);
            constraint23.SetCoefficient(D15, 1);
            constraint23.SetCoefficient(D16, 1);
            constraint23.SetCoefficient(D17, 1);
            constraint23.SetCoefficient(D18, 1);
            constraint23.SetCoefficient(D19, 1);
            constraint23.SetCoefficient(D20, 1);
            constraint23.SetCoefficient(D21, 1);
            constraint23.SetCoefficient(D22, 1);
            constraint23.SetCoefficient(D23, 1);

            Constraint constraint24 = solver.MakeConstraint(8800, 8800);
            constraint24.SetCoefficient(E3, 1);
            constraint24.SetCoefficient(E4, 1);
            constraint24.SetCoefficient(E5, 1);
            constraint24.SetCoefficient(E6, 1);
            constraint24.SetCoefficient(E7, 1);
            constraint24.SetCoefficient(E8, 1);
            constraint24.SetCoefficient(E9, 1);
            constraint24.SetCoefficient(E10, 1);
            constraint24.SetCoefficient(E11, 1);
            constraint24.SetCoefficient(E12, 1);
            constraint24.SetCoefficient(E13, 1);
            constraint24.SetCoefficient(E14, 1);
            constraint24.SetCoefficient(E15, 1);
            constraint24.SetCoefficient(E16, 1);
            constraint24.SetCoefficient(E17, 1);
            constraint24.SetCoefficient(E18, 1);
            constraint24.SetCoefficient(E19, 1);
            constraint24.SetCoefficient(E20, 1);
            constraint24.SetCoefficient(E21, 1);
            constraint24.SetCoefficient(E22, 1);
            constraint24.SetCoefficient(E23, 1);

            Constraint constraint25 = solver.MakeConstraint(8800, 8800);
            constraint25.SetCoefficient(F3, 1);
            constraint25.SetCoefficient(F4, 1);
            constraint25.SetCoefficient(F5, 1);
            constraint25.SetCoefficient(F6, 1);
            constraint25.SetCoefficient(F7, 1);
            constraint25.SetCoefficient(F8, 1);
            constraint25.SetCoefficient(F9, 1);
            constraint25.SetCoefficient(F10, 1);
            constraint25.SetCoefficient(F11, 1);
            constraint25.SetCoefficient(F12, 1);
            constraint25.SetCoefficient(F13, 1);
            constraint25.SetCoefficient(F14, 1);
            constraint25.SetCoefficient(F15, 1);
            constraint25.SetCoefficient(F16, 1);
            constraint25.SetCoefficient(F17, 1);
            constraint25.SetCoefficient(F18, 1);
            constraint25.SetCoefficient(F19, 1);
            constraint25.SetCoefficient(F20, 1);
            constraint25.SetCoefficient(F21, 1);
            constraint25.SetCoefficient(F22, 1);
            constraint25.SetCoefficient(F23, 1);

            Constraint constraint26 = solver.MakeConstraint(8800, 8800);
            constraint26.SetCoefficient(G3, 1);
            constraint26.SetCoefficient(G4, 1);
            constraint26.SetCoefficient(G5, 1);
            constraint26.SetCoefficient(G6, 1);
            constraint26.SetCoefficient(G7, 1);
            constraint26.SetCoefficient(G8, 1);
            constraint26.SetCoefficient(G9, 1);
            constraint26.SetCoefficient(G10, 1);
            constraint26.SetCoefficient(G11, 1);
            constraint26.SetCoefficient(G12, 1);
            constraint26.SetCoefficient(G13, 1);
            constraint26.SetCoefficient(G14, 1);
            constraint26.SetCoefficient(G15, 1);
            constraint26.SetCoefficient(G16, 1);
            constraint26.SetCoefficient(G17, 1);
            constraint26.SetCoefficient(G18, 1);
            constraint26.SetCoefficient(G19, 1);
            constraint26.SetCoefficient(G20, 1);
            constraint26.SetCoefficient(G21, 1);
            constraint26.SetCoefficient(G22, 1);
            constraint26.SetCoefficient(G23, 1);

            Constraint constraint27 = solver.MakeConstraint(8800, 8800);
            constraint27.SetCoefficient(H3, 1);
            constraint27.SetCoefficient(H4, 1);
            constraint27.SetCoefficient(H5, 1);
            constraint27.SetCoefficient(H6, 1);
            constraint27.SetCoefficient(H7, 1);
            constraint27.SetCoefficient(H8, 1);
            constraint27.SetCoefficient(H9, 1);
            constraint27.SetCoefficient(H10, 1);
            constraint27.SetCoefficient(H11, 1);
            constraint27.SetCoefficient(H12, 1);
            constraint27.SetCoefficient(H13, 1);
            constraint27.SetCoefficient(H14, 1);
            constraint27.SetCoefficient(H15, 1);
            constraint27.SetCoefficient(H16, 1);
            constraint27.SetCoefficient(H17, 1);
            constraint27.SetCoefficient(H18, 1);
            constraint27.SetCoefficient(H19, 1);
            constraint27.SetCoefficient(H20, 1);
            constraint27.SetCoefficient(H21, 1);
            constraint27.SetCoefficient(H22, 1);
            constraint27.SetCoefficient(H23, 1);

            Constraint constraint28 = solver.MakeConstraint(8800, 8800);
            constraint28.SetCoefficient(I3, 1);
            constraint28.SetCoefficient(I4, 1);
            constraint28.SetCoefficient(I5, 1);
            constraint28.SetCoefficient(I6, 1);
            constraint28.SetCoefficient(I7, 1);
            constraint28.SetCoefficient(I8, 1);
            constraint28.SetCoefficient(I9, 1);
            constraint28.SetCoefficient(I10, 1);
            constraint28.SetCoefficient(I11, 1);
            constraint28.SetCoefficient(I12, 1);
            constraint28.SetCoefficient(I13, 1);
            constraint28.SetCoefficient(I14, 1);
            constraint28.SetCoefficient(I15, 1);
            constraint28.SetCoefficient(I16, 1);
            constraint28.SetCoefficient(I17, 1);
            constraint28.SetCoefficient(I18, 1);
            constraint28.SetCoefficient(I19, 1);
            constraint28.SetCoefficient(I20, 1);
            constraint28.SetCoefficient(I21, 1);
            constraint28.SetCoefficient(I22, 1);
            constraint28.SetCoefficient(I23, 1);

            Constraint constraint29 = solver.MakeConstraint(7500, 7500);
            constraint29.SetCoefficient(J3, 1);
            constraint29.SetCoefficient(J4, 1);
            constraint29.SetCoefficient(J5, 1);
            constraint29.SetCoefficient(J6, 1);
            constraint29.SetCoefficient(J7, 1);
            constraint29.SetCoefficient(J8, 1);
            constraint29.SetCoefficient(J9, 1);
            constraint29.SetCoefficient(J10, 1);
            constraint29.SetCoefficient(J11, 1);
            constraint29.SetCoefficient(J12, 1);
            constraint29.SetCoefficient(J13, 1);
            constraint29.SetCoefficient(J14, 1);
            constraint29.SetCoefficient(J15, 1);
            constraint29.SetCoefficient(J16, 1);
            constraint29.SetCoefficient(J17, 1);
            constraint29.SetCoefficient(J18, 1);
            constraint29.SetCoefficient(J19, 1);
            constraint29.SetCoefficient(J20, 1);
            constraint29.SetCoefficient(J21, 1);
            constraint29.SetCoefficient(J22, 1);
            constraint29.SetCoefficient(J23, 1);

            Constraint constraint30 = solver.MakeConstraint(7500, 7500);
            constraint30.SetCoefficient(K3, 1);
            constraint30.SetCoefficient(K4, 1);
            constraint30.SetCoefficient(K5, 1);
            constraint30.SetCoefficient(K6, 1);
            constraint30.SetCoefficient(K7, 1);
            constraint30.SetCoefficient(K8, 1);
            constraint30.SetCoefficient(K9, 1);
            constraint30.SetCoefficient(K10, 1);
            constraint30.SetCoefficient(K11, 1);
            constraint30.SetCoefficient(K12, 1);
            constraint30.SetCoefficient(K13, 1);
            constraint30.SetCoefficient(K14, 1);
            constraint30.SetCoefficient(K15, 1);
            constraint30.SetCoefficient(K16, 1);
            constraint30.SetCoefficient(K17, 1);
            constraint30.SetCoefficient(K18, 1);
            constraint30.SetCoefficient(K19, 1);
            constraint30.SetCoefficient(K20, 1);
            constraint30.SetCoefficient(K21, 1);
            constraint30.SetCoefficient(K22, 1);
            constraint30.SetCoefficient(K23, 1);

            Constraint constraint31 = solver.MakeConstraint(11500, 11500);
            constraint31.SetCoefficient(L3, 1);
            constraint31.SetCoefficient(L4, 1);
            constraint31.SetCoefficient(L5, 1);
            constraint31.SetCoefficient(L6, 1);
            constraint31.SetCoefficient(L7, 1);
            constraint31.SetCoefficient(L8, 1);
            constraint31.SetCoefficient(L9, 1);
            constraint31.SetCoefficient(L10, 1);
            constraint31.SetCoefficient(L11, 1);
            constraint31.SetCoefficient(L12, 1);
            constraint31.SetCoefficient(L13, 1);
            constraint31.SetCoefficient(L14, 1);
            constraint31.SetCoefficient(L15, 1);
            constraint31.SetCoefficient(L16, 1);
            constraint31.SetCoefficient(L17, 1);
            constraint31.SetCoefficient(L18, 1);
            constraint31.SetCoefficient(L19, 1);
            constraint31.SetCoefficient(L20, 1);
            constraint31.SetCoefficient(L21, 1);
            constraint31.SetCoefficient(L22, 1);
            constraint31.SetCoefficient(L23, 1);

            Constraint constraint32 = solver.MakeConstraint(8700, 8700);
            constraint32.SetCoefficient(M3, 1);
            constraint32.SetCoefficient(M4, 1);
            constraint32.SetCoefficient(M5, 1);
            constraint32.SetCoefficient(M6, 1);
            constraint32.SetCoefficient(M7, 1);
            constraint32.SetCoefficient(M8, 1);
            constraint32.SetCoefficient(M9, 1);
            constraint32.SetCoefficient(M10, 1);
            constraint32.SetCoefficient(M11, 1);
            constraint32.SetCoefficient(M12, 1);
            constraint32.SetCoefficient(M13, 1);
            constraint32.SetCoefficient(M14, 1);
            constraint32.SetCoefficient(M15, 1);
            constraint32.SetCoefficient(M16, 1);
            constraint32.SetCoefficient(M17, 1);
            constraint32.SetCoefficient(M18, 1);
            constraint32.SetCoefficient(M19, 1);
            constraint32.SetCoefficient(M20, 1);
            constraint32.SetCoefficient(M21, 1);
            constraint32.SetCoefficient(M22, 1);
            constraint32.SetCoefficient(M23, 1);

            Constraint constraint33 = solver.MakeConstraint(8700, 8700);
            constraint33.SetCoefficient(N3, 1);
            constraint33.SetCoefficient(N4, 1);
            constraint33.SetCoefficient(N5, 1);
            constraint33.SetCoefficient(N6, 1);
            constraint33.SetCoefficient(N7, 1);
            constraint33.SetCoefficient(N8, 1);
            constraint33.SetCoefficient(N9, 1);
            constraint33.SetCoefficient(N10, 1);
            constraint33.SetCoefficient(N11, 1);
            constraint33.SetCoefficient(N12, 1);
            constraint33.SetCoefficient(N13, 1);
            constraint33.SetCoefficient(N14, 1);
            constraint33.SetCoefficient(N15, 1);
            constraint33.SetCoefficient(N16, 1);
            constraint33.SetCoefficient(N17, 1);
            constraint33.SetCoefficient(N18, 1);
            constraint33.SetCoefficient(N19, 1);
            constraint33.SetCoefficient(N20, 1);
            constraint33.SetCoefficient(N21, 1);
            constraint33.SetCoefficient(N22, 1);
            constraint33.SetCoefficient(N23, 1);

            Constraint constraint34 = solver.MakeConstraint(11500, 11500);
            constraint34.SetCoefficient(O3, 1);
            constraint34.SetCoefficient(O4, 1);
            constraint34.SetCoefficient(O5, 1);
            constraint34.SetCoefficient(O6, 1);
            constraint34.SetCoefficient(O7, 1);
            constraint34.SetCoefficient(O8, 1);
            constraint34.SetCoefficient(O9, 1);
            constraint34.SetCoefficient(O10, 1);
            constraint34.SetCoefficient(O11, 1);
            constraint34.SetCoefficient(O12, 1);
            constraint34.SetCoefficient(O13, 1);
            constraint34.SetCoefficient(O14, 1);
            constraint34.SetCoefficient(O15, 1);
            constraint34.SetCoefficient(O16, 1);
            constraint34.SetCoefficient(O17, 1);
            constraint34.SetCoefficient(O18, 1);
            constraint34.SetCoefficient(O19, 1);
            constraint34.SetCoefficient(O20, 1);
            constraint34.SetCoefficient(O21, 1);
            constraint34.SetCoefficient(O22, 1);
            constraint34.SetCoefficient(O23, 1);

            Constraint constraint35 = solver.MakeConstraint(11500, 11500);
            constraint35.SetCoefficient(P3, 1);
            constraint35.SetCoefficient(P4, 1);
            constraint35.SetCoefficient(P5, 1);
            constraint35.SetCoefficient(P6, 1);
            constraint35.SetCoefficient(P7, 1);
            constraint35.SetCoefficient(P8, 1);
            constraint35.SetCoefficient(P9, 1);
            constraint35.SetCoefficient(P10, 1);
            constraint35.SetCoefficient(P11, 1);
            constraint35.SetCoefficient(P12, 1);
            constraint35.SetCoefficient(P13, 1);
            constraint35.SetCoefficient(P14, 1);
            constraint35.SetCoefficient(P15, 1);
            constraint35.SetCoefficient(P16, 1);
            constraint35.SetCoefficient(P17, 1);
            constraint35.SetCoefficient(P18, 1);
            constraint35.SetCoefficient(P19, 1);
            constraint35.SetCoefficient(P20, 1);
            constraint35.SetCoefficient(P21, 1);
            constraint35.SetCoefficient(P22, 1);
            constraint35.SetCoefficient(P23, 1);

            Constraint constraint36 = solver.MakeConstraint(11500, 11500);
            constraint36.SetCoefficient(Q3, 1);
            constraint36.SetCoefficient(Q4, 1);
            constraint36.SetCoefficient(Q5, 1);
            constraint36.SetCoefficient(Q6, 1);
            constraint36.SetCoefficient(Q7, 1);
            constraint36.SetCoefficient(Q8, 1);
            constraint36.SetCoefficient(Q9, 1);
            constraint36.SetCoefficient(Q10, 1);
            constraint36.SetCoefficient(Q11, 1);
            constraint36.SetCoefficient(Q12, 1);
            constraint36.SetCoefficient(Q13, 1);
            constraint36.SetCoefficient(Q14, 1);
            constraint36.SetCoefficient(Q15, 1);
            constraint36.SetCoefficient(Q16, 1);
            constraint36.SetCoefficient(Q17, 1);
            constraint36.SetCoefficient(Q18, 1);
            constraint36.SetCoefficient(Q19, 1);
            constraint36.SetCoefficient(Q20, 1);
            constraint36.SetCoefficient(Q21, 1);
            constraint36.SetCoefficient(Q22, 1);
            constraint36.SetCoefficient(Q23, 1);
            /*
            Objective objective = solver.Objective();
            objective.SetCoefficient(C3, 0);
            objective.SetMaximization();  
            */

            // 求解问题
            solver.Solve();

            // 输出结果
            MessageBox.Show("C3 = " + C3.SolutionValue());
            MessageBox.Show("C4 = " + C4.SolutionValue());
            MessageBox.Show("C5 = " + C5.SolutionValue());
            MessageBox.Show("D3 = " + D3.SolutionValue());
            MessageBox.Show("D4 = " + D4.SolutionValue());
            MessageBox.Show("D5 = " + D5.SolutionValue());
            MessageBox.Show("E3 = " + E3.SolutionValue());
            MessageBox.Show("E4 = " + E4.SolutionValue());
            MessageBox.Show("E5 = " + E5.SolutionValue());


        }
    }

    

}
